name: jaxstack
channels:
  - conda-forge
dependencies:
  - cuda-nvcc
  - ipykernel
  - ipywidgets
  - jupyterlab
  - jupyterlab_widgets
  - matplotlib
  - numpy
  - pandas=2.3
  - pip
  - python=3.11
  - scikit-learn=1.7
  - scipy=1.14
  - setuptools
  - pip:
    - GitPython==3.1.43
    - Markdown==3.7
    - MarkupSafe==2.1.5
    - Pygments==2.18.0
    - Werkzeug==3.0.4
    - absl-py==2.1.0
    - accelerate==1.10.1
    - aiofiles==24.1.0
    - anyio==4.9.0
    - array_record==0.5.1
    - arrow==1.3.0
    - asttokens==2.4.1
    - astunparse==1.6.3
    - attrs==25.3.0
    - beautifulsoup4==4.13.4
    - bleach==6.2.0
    - certifi==2024.8.30
    - chex==0.1.89
    - click==8.1.7
    - comm==0.2.2
    - contextlib2==21.6.0
    - contourpy==1.3.0
    - dataclasses-json==0.6.7
    - debugpy==1.8.5
    - decorator==5.1.1
    - diffrax==0.6.0
    - diffusers==0.35.1
    - dm-tree==0.1.8
    - docker-pycreds==0.4.0
    - docstring_parser==0.16
    - equinox==0.11.6
    - etils==1.9.4
    - exceptiongroup==1.2.2
    - executing==2.1.0
    - fastjsonschema==2.21.1
    - filelock==3.20.0
    - flatbuffers==24.3.25
    - flax==0.10.5
    - fonttools==4.53.1
    - fsspec==2024.9.0
    - gast==0.6.0
    - gitdb==4.0.11
    - google-pasta==0.2.0
    - googleapis-common-protos==1.72.0
    - grpcio==1.66.1
    - h5py==3.11.0
    - hf-xet==1.1.8
    - huggingface-hub==0.34.4
    - humanize==4.10.0
    - idna==3.10
    - imageio==2.37.0
    - immutabledict==4.2.0
    - importlib_resources==6.4.5
    - ipykernel==6.29.5
    - ipython==8.27.0
    - ipywidgets==8.1.7
    - jax==0.5.3
    - jax-ai-stack==2025.4.9
    - jax-cuda12-pjrt==0.5.3
    - jax-cuda12-plugin==0.5.3
    - jaxlib==0.5.3
    - jaxtyping==0.2.34
    - jedi==0.19.1
    - joblib==1.5.1
    - json5==0.12.0
    - jsonschema==4.25.0
    - jsonschema-specifications==2025.4.1
    - jupyter==1.1.1
    - jupyter-console==6.6.3
    - jupyter-lsp==2.2.6
    - jupyter_core==5.7.2
    - jupyter_server==2.16.0
    - jupyterlab==4.4.5
    - jupyterlab-mathjax3==4.3.0
    - jupyterlab_server==2.27.3
    - jupyterlab_widgets==3.0.15
    - keras==3.5.0
    - kiwisolver==1.4.7
    - lark==1.2.2
    - libclang==18.1.1
    - lineax==0.0.5
    - llvmlite==0.44.0
    - markdown-it-py==3.0.0
    - marshmallow==3.26.1
    - mathjax==0.1.2
    - matplotlib==3.9.2
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.1.3
    - ml_collections==0.1.1
    - ml_dtypes==0.5.1
    - mpmath==1.3.0
    - msgpack==1.1.0
    - mypy_extensions==1.1.0
    - namex==0.0.8
    - networkx==3.6.1
    - notebook==7.4.4
    - numba==0.61.2
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu12==12.4.127
    - opt-einsum==3.3.0
    - optax==0.2.4
    - optimistix==0.0.7
    - optree==0.12.1
    - optype==0.15.0
    - orbax-checkpoint==0.11.12
    - orbax-export==0.0.6
    - packaging==24.1
    - pandas==2.3.1
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pillow==10.4.0
    - pip==24.3.1
    - platformdirs==4.3.4
    - prometheus_client==0.22.1
    - promise==2.3
    - prompt_toolkit==3.0.47
    - protobuf==4.25.8
    - psutil==6.0.0
    - pyarrow==17.0.0
    - pynndescent==0.5.13
    - pyparsing==3.1.4
    - python-box==7.3.2
    - python-json-logger==3.3.0
    - pyzmq==26.2.0
    - referencing==0.36.2
    - regex==2025.7.34
    - requests==2.32.3
    - rich==13.8.1
    - rpds-py==0.26.0
    - safetensors==0.6.2
    - scikit-learn==1.7.1
    - scipy-stubs==1.14.1.6
    - seaborn==0.13.2
    - sentry-sdk==2.14.0
    - setproctitle==1.3.3
    - setuptools
    - simple-parsing==0.1.6
    - simplejson==3.20.1
    - six==1.16.0
    - smmap==5.0.1
    - soupsieve==2.7
    - sympy==1.13.1
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - tensorflow==2.19.0
    - tensorflow-datasets==4.9.8
    - tensorflow-io-gcs-filesystem==0.37.1
    - tensorflow-metadata==1.15.0
    - tensorstore==0.1.76
    - termcolor==2.4.0
    - tinycss2==1.4.0
    - tokenizers==0.21.4
    - toml==0.10.2
    - tomli==2.2.1
    - toolz==0.12.1
    - torch==2.5.1
    - torchaudio==2.5.1
    - torchvision==0.20.1
    - tornado==6.4.1
    - tqdm==4.66.5
    - transformers==4.55.4
    - treescope==0.1.9
    - triton==3.1.0
    - typeguard==2.13.3
    - types-python-dateutil==2.9.0.20250708
    - typing-inspect==0.9.0
    - umap-learn==0.5.9.post2
    - urllib3==2.2.3
    - wandb==0.18.1
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - websocket-client==1.8.0
    - widgetsnbextension==4.0.14
    - wrapt==1.16.0
    - zipp==3.20.2

prefix: "/home/molefe/miniforge3/envs/jaxstack"
